### ISSUE TITLE
receipt-data

### ISSUE THREAD

**Issue by mkeremkeskin** [pradeep7may/InAppPurchase#1]
Hi;

In `(BOOL)verifyReceipt` method the below dictionary is being used. What does it do, can you please explain it?

```
NSDictionary *jsonDict = [NSDictionary dictionaryWithObjectsAndKeys:recieptString,@"receipt-data",@"827d5be5c5944b3db18bbb0278c3e8bd",@"password", nil];
```

**Comment by pradeep7may** [comment]
Hi,

This is the dictionary that you use to verify the receipt data. Here receipt-data key contains the receipt string that need to be verified and password is the hexadecimal shared secret for the app. The password is used only in case of autorenewable subscription.

Hope this will solve your query.

Let me know if you want any other clarification.

Thanks
